### ISSUE TITLE
GitHub actions

### ISSUE THREAD

**Issue by bbaassssiiee** [dockpack/base_nettime#2]

**Comment by rohan2734** [comment]
hey i would like to work on it, can you elaborate the issue?

**Comment by bbaassssiiee** [comment]
I'd like to run GitHub actions instead of Travis. Molecule...

**Comment by rohan2734** [comment]
Hey can you assign me i would like to work on it

**Comment by bbaassssiiee** [comment]
Just fork the repo and create a pull-request. Don't forget to register for #Hacktoberfest!

**Comment by rohan2734** [comment]
ok

**Comment by bbaassssiiee** [comment]
The .travis.yml installs the python requirements to run toc. Tox uses tox.ini to run tests.

**Comment by rohan2734** [comment]
> The .travis.yml installs the python requirements to run toc. Tox uses tox.ini to run tests.

i didnt get you, how to setup this? are there any steps for the setup?

**Comment by bbaassssiiee** [comment]
Look in the .travis.yml

**Comment by rohan2734** [comment]
bro actually i have no idea of python, i am a good js developer, so will i be able to do?

**Comment by bbaassssiiee** [comment]
This repo is an Ansible role to configure time synchronization. Ansible is written in python, tox test this repo with multiple versions of ansible in multiple versions of python. It might be too technical for you.

**Comment by rohan2734** [comment]
@bbaassssiiee  ya may be. but you can tell me what are the things i need to add, as we need to add a script to run the app automatically , like ```run index.py```, so is there any file like that?
